### ISSUE TITLE
Local excel file association can spoil file validation

### ISSUE THREAD

**Issue by jimlane** [Azure-Samples/Serverless-File-Validation#1]
Helpers.ParseEventGridPayload inspects metadata passed from the EventGrid subscription. One of those items is contentType which will fail for anything other than text/csv. However, if you download the sample files to a local machine that has a file association for all CSV files to MS Excel, this value will appear as application/vnd.ms-excel when you drop them into a storage account. 
 
I modified the logical AND operator for content type to a logical OR instead to get it working for me. :-)

![helpers](https://user-images.githubusercontent.com/12076673/81205795-2dd62a80-8f99-11ea-8ea6-f79fb3cc3f9d.png)

**Comment by brandonh-msft** [comment]
Thanks Jim,

Great call-out and glad you got it working! Since somebody could associate a csv with any application, I'm not sure we want to start down the path of solving for this exact problem but rather in the spirit of git instead let people such as yourself modified the code to fit their needs with this sample serving exactly as a sample :)

Thanks for enlightening the community with your problem & approach, though!

**Comment by jimlane** [comment]
I gotcha, and agree with the overall desire to limit dependencies for local machines, but this code does exactly that. The only way this code executes successfully is in a scenario where this file association exists.
